name: Release

on:
  push:
    tags: [ '**' ]

permissions:
  contents: read

jobs:
  windows:
    uses: 9506hqwy/actions/.github/workflows/rust-release-windows.yml@main

  release:

    needs: [windows]

    permissions:
      contents: write

    uses: 9506hqwy/actions/.github/workflows/common-create-release.yml@main
    with:
      title-prefix: v
